services:
  api:
    build:
      context: .
      dockerfile: Backend/WebAPI/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=TesteDB;Username=postgres;Password=postgres;Port=5432
    depends_on:
      - db
    networks:
      - app-network

  mvc:
    build:
      context: .
      dockerfile: Frontend/mvc/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://api/api/
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - "5433:5432"  # Mapeia a porta 5433 do host para a 5432 do contêiner
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TesteDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: